sudo: required
dist: trusty

branches:
  only:
   - master android

matrix:
  include:
    - language: android
        sudo: true
        android:
          components:
            - tools
            - platform-tools
            - build-tools-25.0.2
            - android-25
            - extra-android-m2repository
        compiler:
          - gcc
        before_install:
          - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
          - export ANDROID_NDK_HOME=$HOME/android-ndk-root
          # Setup environment for Linux build which is required to build the sample.
          - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
          - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
          - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq g++-$GCC_VERSION; fi
          - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq gcc-$GCC_VERSION; fi
          - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s -v -f $(which g++-$GCC_VERSION) /usr/bin/g++; fi
          - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s -v -f $(which gcc-$GCC_VERSION) /usr/bin/gcc; fi
        script:
        # Obtain bench reference from git log
        - git log HEAD | grep "\b[Bb]ench[ :]\+[0-9]\{7\}" | head -n 1 | sed "s/[^0-9]*\([0-9]*\).*/\1/g" > git_sig
        - export benchref=$(cat git_sig)
        - echo "Reference bench:" $benchref
        #
        # Verify bench number against various builds
        - export CXXFLAGS=-Werror
        - make clean && make ARCH=armv7 debug=yes build && ../tests/signature.sh $benchref

